/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TarifasRouteImport } from './routes/tarifas'
import { Route as SeguridadRouteImport } from './routes/seguridad'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as CoberturaRouteImport } from './routes/cobertura'
import { Route as IndexRouteImport } from './routes/index'

const TarifasRoute = TarifasRouteImport.update({
  id: '/tarifas',
  path: '/tarifas',
  getParentRoute: () => rootRouteImport,
} as any)
const SeguridadRoute = SeguridadRouteImport.update({
  id: '/seguridad',
  path: '/seguridad',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const CoberturaRoute = CoberturaRouteImport.update({
  id: '/cobertura',
  path: '/cobertura',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cobertura': typeof CoberturaRoute
  '/contacto': typeof ContactoRoute
  '/seguridad': typeof SeguridadRoute
  '/tarifas': typeof TarifasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cobertura': typeof CoberturaRoute
  '/contacto': typeof ContactoRoute
  '/seguridad': typeof SeguridadRoute
  '/tarifas': typeof TarifasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cobertura': typeof CoberturaRoute
  '/contacto': typeof ContactoRoute
  '/seguridad': typeof SeguridadRoute
  '/tarifas': typeof TarifasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cobertura' | '/contacto' | '/seguridad' | '/tarifas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cobertura' | '/contacto' | '/seguridad' | '/tarifas'
  id: '__root__' | '/' | '/cobertura' | '/contacto' | '/seguridad' | '/tarifas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoberturaRoute: typeof CoberturaRoute
  ContactoRoute: typeof ContactoRoute
  SeguridadRoute: typeof SeguridadRoute
  TarifasRoute: typeof TarifasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tarifas': {
      id: '/tarifas'
      path: '/tarifas'
      fullPath: '/tarifas'
      preLoaderRoute: typeof TarifasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seguridad': {
      id: '/seguridad'
      path: '/seguridad'
      fullPath: '/seguridad'
      preLoaderRoute: typeof SeguridadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cobertura': {
      id: '/cobertura'
      path: '/cobertura'
      fullPath: '/cobertura'
      preLoaderRoute: typeof CoberturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoberturaRoute: CoberturaRoute,
  ContactoRoute: ContactoRoute,
  SeguridadRoute: SeguridadRoute,
  TarifasRoute: TarifasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
